name: money_tracker
description: "A new Flutter project."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.11.0
  melos: ^6.3.3

flutter:
  uses-material-design: true
  fonts:
    - family: LineSeedSansTH
      fonts:
        - asset: ./assets/fonts/LINESeedSansTH_A_Rg.ttf
          weight: 400
        - asset: ./assets/fonts/LINESeedSansTH_A_Bd.ttf
          weight: 500

flutter_gen:
  output: ./modules/core/lib/gen
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: Assets
