name: money_tracker
description: "A new Flutter project."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^6.3.3

flutter:
  uses-material-design: true
  fonts:
    - family: LineSeedSansTH
      fonts:
        - asset: ./modules/core/assets/fonts/LINESeedSansTH_A_Rg.ttf
          weight: 400
        - asset: ./modules/core/assets/fonts/LINESeedSansTH_A_Bd.ttf
          weight: 500
