name: core
description: "Core module for money_tracker application"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  copy_with_extension: ^9.1.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  synchronized: ^3.4.0
  ua_client_hints: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  copy_with_extension_gen: ^9.1.0
  intl_utils: ^2.8.11

flutter:

flutter_intl:
  enabled: true
  main_locale: th
  class_name: CoreLocalizations
  arb_dir: lib/src/l10n
  output_dir: lib/gen
